# Generated by Django 2.2.15 on 2020-08-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0002_auto_20200217_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdobeCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkey', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),  # noqa
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
