# Generated by Django 2.2.9 on 2020-01-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalbasis',
            options={'verbose_name_plural': 'LegalBases'},
        ),
    ]
