# Generated by Django 2.2.10 on 2020-02-18 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalbasis",
            name="modified_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
