# Generated by Django 2.2.10 on 2020-03-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_consent_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalBasisCurrent",
            fields=[],
            options={
                "verbose_name_plural": "Current LegalBases",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.legalbasis",),
        ),
    ]
