# Generated by Django 4.2.11 on 2024-04-12 15:49
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200325_1554"),
    ]

    operations = [
        CreateCollation(
            "create_case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
    ]

