# Generated by Django 4.2.11 on 2024-04-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_create_case_insensitive_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="extra",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="legalbasis",
            name="email",
            field=models.EmailField(
                blank=True,
                db_collation="create_case_insensitive",
                db_index=True,
                max_length=254,
            ),
        ),
    ]
